runtime: python314
service: citas-cliente
basic_scaling:
  max_instances: 2
  idle_timeout: 10m

handlers:
  # Maneja la ruta raíz
  - url: /
    static_files: index.html
    upload: index.html

  # Maneja el logo y otros archivos estáticos
  - url: /(.*)
    static_files: \1
    upload: (.*)
