runtime: python39
service: citas-cliente

handlers:
  # Maneja la ruta raíz
  - url: /
    static_files: index.html
    upload: index.html

  # Maneja el logo y otros archivos estáticos
  - url: /(.*)
    static_files: \1
    upload: (.*)
